version: "3.8"

services:
  robot:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ros2 launch robot_bringup only_robot.launch.py
  robot_station:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ros2 launch robot_bringup only_robot_station.launch.py
    depends_on:
      - robot
  points_spawner:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ros2 launch robot_bringup only_points_spawner.launch.py
    depends_on:
      - robot_station